/**
 * Cursor Rules Generator
 * Generates .cursorrules files with Paradigm system context
 */

import * as fs from 'fs';
import * as path from 'path';
import { ParadigmConfig } from './paradigm-config';
import { getScanProtocol } from '@a-company/probe-core';

export type CursorRulesMode = 'create' | 'append' | 'skip';

const START_MARKER = '<!-- HORIZON:START -->';
const END_MARKER = '<!-- HORIZON:END -->';

export interface CursorrrulesOptions {
  /** Include scan protocol section */
  withScan?: boolean;
  /** Custom scan instructions */
  scanInstructions?: string[];
}

/**
 * Generate .cursorrules content from Paradigm config
 */
export function generateCursorrules(
  config: ParadigmConfig, 
  projectName?: string,
  options: CursorrrulesOptions = {}
): string {
  const lines: string[] = [];

  // Header
  lines.push('# Project Context (via Paradigm)');
  lines.push('');
  
  if (projectName) {
    lines.push(`Project: ${projectName}`);
    lines.push('');
  }
  
  // Overview
  if (config['agent-guidelines']?.overview) {
    lines.push(config['agent-guidelines'].overview);
    lines.push('');
  }

  lines.push('This project uses Paradigm for structured AI context:');
  lines.push('- `.purpose` files define features, components, and context');
  lines.push('- `portal.yaml` files define authorization topology');
  lines.push('- `.premise` files aggregate everything into the Dreamscape');
  lines.push('');

  // How to use
  if (config['agent-guidelines']?.['how-to-use']?.length) {
    lines.push('## How to Use Paradigm');
    lines.push('');
    for (const instruction of config['agent-guidelines']['how-to-use']) {
      lines.push(`- ${instruction}`);
    }
    lines.push('');
  }

  // Symbol System
  lines.push('## Symbol System');
  lines.push('');
  lines.push('Use these prefixes to reference project elements:');
  lines.push('');
  lines.push('| Symbol | Name | Owner | Examples |');
  lines.push('|--------|------|-------|----------|');
  
  const symbolSystem = config['symbol-system'];
  if (symbolSystem) {
    for (const [prefix, def] of Object.entries(symbolSystem)) {
      const examples = def.examples?.slice(0, 2).join(', ') || '';
      lines.push(`| \`${prefix}\` | ${def.name} | ${def.owner} | ${examples} |`);
    }
  }
  lines.push('');

  // Symbol Details
  lines.push('### Symbol Details');
  lines.push('');
  if (symbolSystem) {
    for (const [prefix, def] of Object.entries(symbolSystem)) {
      lines.push(`- **\`${prefix}\` ${def.name}** (${def.owner}): ${def.description}`);
    }
  }
  lines.push('');

  // State Definitions
  if (config.states && Object.keys(config.states).length > 0) {
    lines.push('## Defined States');
    lines.push('');
    
    for (const [category, states] of Object.entries(config.states)) {
      if (typeof states === 'object' && states !== null) {
        for (const [stateName, stateValue] of Object.entries(states)) {
          const description = getStateDescription(stateValue);
          lines.push(`- \`%${category}.${stateName}\` - ${description}`);
        }
      }
    }
    lines.push('');
  }

  // Update Rules
  if (config['agent-guidelines']?.['update-rules']?.length) {
    lines.push('## When to Update Paradigm Files');
    lines.push('');
    for (const rule of config['agent-guidelines']['update-rules']) {
      lines.push(`- ${rule}`);
    }
    lines.push('');
  }

  // Conventions
  if (config.conventions?.length) {
    lines.push('## Conventions');
    lines.push('');
    for (const convention of config.conventions) {
      lines.push(`- ${convention}`);
    }
    lines.push('');
  }

  // Paradigm Commands
  lines.push('## Paradigm Commands');
  lines.push('');
  lines.push('| Command | Description |');
  lines.push('|---------|-------------|');
  lines.push('| `paradigm init` | Initialize Paradigm in a project |');
  lines.push('| `paradigm status` | Show project symbol status |');
  lines.push('| `paradigm visualize` | Open the Dreamscape visualizer |');
  lines.push('| `paradigm purpose validate` | Validate .purpose files |');
  lines.push('| `paradigm gate validate` | Validate portal.yaml files |');
  lines.push('| `paradigm dream aggregate` | Aggregate all symbols |');
  lines.push('| `paradigm cursorrules` | Regenerate this .cursorrules file |');
  lines.push('');

  // Purpose File Locations
  if (config['purpose-required']?.length) {
    lines.push('## Purpose File Locations');
    lines.push('');
    lines.push('`.purpose` files should exist in:');
    for (const req of config['purpose-required']) {
      lines.push(`- \`${req.pattern}\` (depth: ${req.depth})`);
    }
    lines.push('');
  }

  // Scan Protocol (if enabled)
  if (options.withScan) {
    lines.push('');
    lines.push(getScanProtocol({
      projectName,
      customInstructions: options.scanInstructions,
    }));
    lines.push('');
  }

  // Footer
  lines.push('---');
  lines.push('*Generated by Paradigm. Update `.paradigm` config and run `paradigm cursorrules` to regenerate.*');

  return lines.join('\n');
}

/**
 * Get description from state definition
 */
function getStateDescription(state: unknown): string {
  if (typeof state === 'boolean') {
    return 'Boolean state';
  }
  if (typeof state === 'object' && state !== null) {
    const s = state as Record<string, unknown>;
    if (s.description) {
      return String(s.description);
    }
    if (s.type) {
      if (s.type === 'enum' && Array.isArray(s.values)) {
        return `${s.type} (${s.values.join(', ')})`;
      }
      return String(s.type);
    }
  }
  return 'State';
}

/**
 * Write .cursorrules file
 */
export function writeCursorrules(
  rootDir: string,
  config: ParadigmConfig,
  mode: CursorRulesMode,
  projectName?: string,
  options: CursorrrulesOptions = {}
): { success: boolean; path: string; message: string } {
  if (mode === 'skip') {
    return { success: true, path: '', message: 'Skipped .cursorrules generation' };
  }

  const cursorrrulesPath = path.join(rootDir, '.cursorrules');
  const content = generateCursorrules(config, projectName, options);

  if (mode === 'append' && fs.existsSync(cursorrrulesPath)) {
    // Append mode - wrap in markers
    let existing = fs.readFileSync(cursorrrulesPath, 'utf8');

    // Check if markers already exist
    const startIdx = existing.indexOf(START_MARKER);
    const endIdx = existing.indexOf(END_MARKER);

    const wrappedContent = `\n${START_MARKER}\n${content}\n${END_MARKER}\n`;

    if (startIdx !== -1 && endIdx !== -1) {
      // Replace existing Paradigm section
      existing = existing.substring(0, startIdx) + wrappedContent + existing.substring(endIdx + END_MARKER.length);
    } else {
      // Append to end
      existing = existing.trimEnd() + '\n' + wrappedContent;
    }

    fs.writeFileSync(cursorrrulesPath, existing, 'utf8');
    return {
      success: true,
      path: cursorrrulesPath,
      message: 'Updated .cursorrules with Paradigm section'
    };
  } else {
    // Create mode - write new file
    fs.writeFileSync(cursorrrulesPath, content, 'utf8');
    return {
      success: true,
      path: cursorrrulesPath,
      message: 'Created .cursorrules'
    };
  }
}

/**
 * Check if .cursorrules exists
 */
export function cursorrrulesExists(rootDir: string): boolean {
  return fs.existsSync(path.join(rootDir, '.cursorrules'));
}

/**
 * Check if .paradigm config exists
 */
export function paradigmConfigExists(rootDir: string): boolean {
  return fs.existsSync(path.join(rootDir, '.paradigm'));
}
