/**
 * horizon summary - Generate project.md with stats
 */

import * as fs from 'fs';
import * as path from 'path';
import chalk from 'chalk';
import ora from 'ora';
import { aggregateFromDirectory } from '@horizon/dream-core';
import { detectIDE, getAdapter } from '../core/ide-adapters/index.js';

export async function summaryCommand() {
  const cwd = process.cwd();
  const projectName = path.basename(cwd);
  const spinner = ora();

  console.log(chalk.blue('\n📊 Horizon Summary\n'));

  // Check for .horizon directory
  const horizonDir = path.join(cwd, '.horizon');
  if (!fs.existsSync(horizonDir) || !fs.statSync(horizonDir).isDirectory()) {
    console.log(chalk.red('❌ No .horizon/ directory found.'));
    console.log(chalk.gray('   Run `horizon init` first.\n'));
    process.exit(1);
  }

  // Aggregate symbols
  spinner.start('Aggregating symbols...');
  let aggregation;
  try {
    aggregation = await aggregateFromDirectory(cwd);
    spinner.succeed(`Found ${aggregation.symbols.length} symbols`);
  } catch (error) {
    spinner.fail(chalk.red('Failed to aggregate symbols'));
    console.error(chalk.gray((error as Error).message));
    process.exit(1);
  }

  // Count by type
  const counts: Record<string, { count: number; examples: string[] }> = {
    features: { count: 0, examples: [] },
    components: { count: 0, examples: [] },
    flows: { count: 0, examples: [] },
    gates: { count: 0, examples: [] },
    signals: { count: 0, examples: [] },
    state: { count: 0, examples: [] },
    ideas: { count: 0, examples: [] },
  };

  for (const symbol of aggregation.symbols) {
    const type = symbol.type;
    const key = type === 'feature' ? 'features'
      : type === 'component' ? 'components'
      : type === 'flow' ? 'flows'
      : type === 'gate' ? 'gates'
      : type === 'signal' ? 'signals'
      : type === 'state' ? 'state'
      : type === 'idea' ? 'ideas'
      : null;
    
    if (key && counts[key]) {
      counts[key].count++;
      if (counts[key].examples.length < 3) {
        counts[key].examples.push(symbol.symbol);
      }
    }
  }

  // Check health
  const health: { check: string; status: 'ok' | 'warn' | 'missing' }[] = [];
  
  // Config
  if (fs.existsSync(path.join(horizonDir, 'config.yaml'))) {
    health.push({ check: 'Config', status: 'ok' });
  } else {
    health.push({ check: 'Config', status: 'missing' });
  }
  
  // Specs
  const specsExist = ['logger.md', 'scan.md', 'symbols.md'].every(
    f => fs.existsSync(path.join(horizonDir, 'specs', f))
  );
  health.push({ check: 'Specs', status: specsExist ? 'ok' : 'warn' });
  
  // Docs
  const docsExist = fs.existsSync(path.join(horizonDir, 'docs'));
  health.push({ check: 'Docs', status: docsExist ? 'ok' : 'warn' });
  
  // IDE sync
  const detection = detectIDE(cwd);
  if (detection.detected) {
    const adapter = getAdapter(detection.detected);
    if (adapter && fs.existsSync(path.join(cwd, adapter.outputPath))) {
      health.push({ check: `IDE (${detection.detected})`, status: 'ok' });
    } else {
      health.push({ check: `IDE (${detection.detected})`, status: 'warn' });
    }
  }
  
  // Scan index
  const scanIndexExists = fs.existsSync(path.join(horizonDir, 'scan-index.json'))
    || fs.existsSync(path.join(cwd, '.horizon-scan-index.json'));
  health.push({ check: 'Scan index', status: scanIndexExists ? 'ok' : 'missing' });

  // Generate markdown content
  const lines: string[] = [];
  
  lines.push(`# Project: ${projectName}`);
  lines.push('');
  lines.push(`**Generated:** ${new Date().toISOString()}`);
  lines.push(`**Horizon Version:** 0.2.0`);
  lines.push('');
  
  lines.push('## Symbol Counts');
  lines.push('');
  lines.push('| Type | Count | Examples |');
  lines.push('|------|-------|----------|');
  
  for (const [key, data] of Object.entries(counts)) {
    if (data.count > 0) {
      const examples = data.examples.join(', ');
      lines.push(`| ${key} | ${data.count} | ${examples} |`);
    }
  }
  lines.push('');
  
  lines.push('## Source Files');
  lines.push('');
  lines.push(`- Purpose files: ${aggregation.purposeFiles.length}`);
  lines.push(`- Gate files: ${aggregation.gateFiles.length}`);
  lines.push('');
  
  lines.push('## Health Status');
  lines.push('');
  for (const item of health) {
    const icon = item.status === 'ok' ? '✓' : item.status === 'warn' ? '⚠' : '○';
    lines.push(`- ${icon} ${item.check}`);
  }
  lines.push('');
  
  lines.push('---');
  lines.push('*Generated by `horizon summary`*');

  // Write project.md
  const outputPath = path.join(horizonDir, 'project.md');
  spinner.start('Writing project.md...');
  
  try {
    fs.writeFileSync(outputPath, lines.join('\n'), 'utf8');
    spinner.succeed(chalk.green('project.md generated'));
  } catch (error) {
    spinner.fail(chalk.red('Failed to write project.md'));
    console.error(chalk.gray((error as Error).message));
    process.exit(1);
  }

  // Display summary
  console.log(chalk.gray(`\n  Path: ${outputPath}\n`));
  
  console.log(chalk.white('  Symbol Counts:'));
  for (const [key, data] of Object.entries(counts)) {
    if (data.count > 0) {
      console.log(chalk.gray(`    ${key}: ${data.count}`));
    }
  }
  
  console.log('');
  console.log(chalk.white('  Health:'));
  for (const item of health) {
    const icon = item.status === 'ok' ? chalk.green('✓') 
      : item.status === 'warn' ? chalk.yellow('⚠') 
      : chalk.gray('○');
    console.log(`    ${icon} ${item.check}`);
  }
  
  console.log('');
}
