/**
 * AGENTS.md Adapter
 * Generates AGENTS.md — the universal AI agent instruction file
 * (Cross-IDE standard backed by Google, OpenAI, Cursor, and others)
 *
 * AGENTS.md is a pure-markdown file at repo root. Unlike IDE-specific adapters,
 * it has no MCP configuration or nested contexts — just instructions.
 */

import * as fs from 'fs';
import * as path from 'path';
import type { IDEAdapter, ParadigmFiles } from './types.js';
import {
  generateOverview,
  generateSymbolSystem,
  generateLoggingRules,
  generateConventions,
  generateUpdateRules,
  generateCommandsReference,
  generateNavigationSection,
  generateCommitConvention,
  generateMcpToolReference,
  generateWorkflowProtocol,
  generateHandoffProtocol,
} from './base.js';

export class AgentsAdapter implements IDEAdapter {
  readonly name = 'agents';
  readonly displayName = 'AGENTS.md';
  readonly outputPath = 'AGENTS.md';
  readonly multiFile = false;

  detect(rootDir: string): boolean {
    return fs.existsSync(path.join(rootDir, 'AGENTS.md'));
  }

  generate(files: ParadigmFiles): string {
    const { config, projectName } = files;
    const sections: string[] = [];

    // Header
    sections.push(`# ${projectName} - AI Agent Instructions`);
    sections.push('');
    sections.push('> Generated by [Paradigm](https://github.com/anthropics/paradigm) v2.0 | Universal AI agent instruction file');
    sections.push('');

    // Project overview
    sections.push(generateOverview(config));

    // Symbol system
    sections.push(generateSymbolSystem(config));

    // Conventions
    const conventionsSection = generateConventions(config);
    if (conventionsSection) {
      sections.push(conventionsSection);
    }

    // Logging rules
    const loggingSection = generateLoggingRules(config);
    if (loggingSection) {
      sections.push(loggingSection);
    }

    // MCP tools reference (new shared generator)
    sections.push(generateMcpToolReference());

    // Navigation
    sections.push(generateNavigationSection(config));

    // Workflow protocol (new shared generator)
    sections.push(generateWorkflowProtocol());

    // Commit conventions
    sections.push(generateCommitConvention());

    // Session recovery & handoff (new shared generator)
    sections.push(generateHandoffProtocol());

    // Update rules
    const updateSection = generateUpdateRules(config);
    if (updateSection) {
      sections.push(updateSection);
    }

    // CLI commands reference
    sections.push(generateCommandsReference());

    // Footer
    sections.push('---');
    sections.push('');
    sections.push('*Generated by Paradigm. Run `paradigm sync agents` to regenerate.*');

    return sections.filter(s => s !== undefined && s !== '').join('\n');
  }
}

export const agentsAdapter = new AgentsAdapter();
