/**
 * GitHub Copilot IDE Adapter
 * Generates .github/instructions/*.instructions.md files (modern format)
 * 
 * The modern Copilot format uses multiple instruction files with YAML frontmatter
 * for scoping via `applyTo` glob patterns. This is more efficient than a single
 * copilot-instructions.md file because instructions only apply to matching files.
 */

import * as fs from 'fs';
import * as path from 'path';
import type { IDEAdapter, ParadigmFiles, GeneratedFile } from './types.js';
import {
  generateOverview,
  generateSymbolSystem,
  generateLoggingRules,
  generateConventions,
  generateUpdateRules,
  generateCommandsReference,
  generateCommitConvention,
} from './base.js';

/**
 * Generate YAML frontmatter for .instructions.md files
 */
function frontmatter(applyTo?: string, excludeAgent?: string): string {
  if (!applyTo && !excludeAgent) {
    return '';
  }
  
  const lines = ['---'];
  
  if (applyTo) {
    lines.push(`applyTo: "${applyTo}"`);
  }
  
  if (excludeAgent) {
    lines.push(`excludeAgent: "${excludeAgent}"`);
  }
  
  lines.push('---', '');
  return lines.join('\n');
}

export class CopilotAdapter implements IDEAdapter {
  readonly name = 'copilot';
  readonly displayName = 'GitHub Copilot';
  readonly outputPath = '.github/instructions';
  readonly multiFile = true;

  detect(rootDir: string): boolean {
    // Check for existing copilot instructions (modern)
    if (fs.existsSync(path.join(rootDir, '.github', 'instructions'))) {
      return true;
    }
    
    // Check for existing copilot instructions (legacy)
    if (fs.existsSync(path.join(rootDir, '.github', 'copilot-instructions.md'))) {
      return true;
    }
    
    return false;
  }

  /**
   * Generate single file content (legacy fallback)
   */
  generate(files: ParadigmFiles): string {
    // For backwards compatibility, return combined content
    const generatedFiles = this.generateFiles(files);
    return generatedFiles.map(f => `# ${f.path}\n\n${f.content}`).join('\n\n---\n\n');
  }

  /**
   * Generate multiple .instructions.md files for the modern Copilot format
   */
  generateFiles(files: ParadigmFiles): GeneratedFile[] {
    const { config, projectName } = files;
    const generatedFiles: GeneratedFile[] = [];

    // 1. Core instructions (no frontmatter = applies globally via copilot-instructions.md)
    // Note: We generate this as the main copilot-instructions.md for always-apply rules
    generatedFiles.push({
      path: '../copilot-instructions.md', // Goes to .github/copilot-instructions.md
      content: this.generateCoreInstructions(projectName, config),
    });

    // 2. Symbol system (TypeScript/JavaScript)
    generatedFiles.push({
      path: 'paradigm-symbols.instructions.md',
      content: this.generateSymbolInstructions(config),
    });

    // 3. Logging instructions (TypeScript/JavaScript)
    const loggingContent = generateLoggingRules(config);
    if (loggingContent) {
      generatedFiles.push({
        path: 'paradigm-logging.instructions.md',
        content: this.generateLoggingInstructions(config),
      });
    }

    // 4. Purpose file instructions
    generatedFiles.push({
      path: 'paradigm-purpose.instructions.md',
      content: this.generatePurposeInstructions(),
    });

    // 5. Portal instructions
    generatedFiles.push({
      path: 'paradigm-portal.instructions.md',
      content: this.generatePortalInstructions(),
    });

    // 6. Conventions (TypeScript/JavaScript)
    generatedFiles.push({
      path: 'paradigm-conventions.instructions.md',
      content: this.generateConventionsInstructions(config),
    });

    // 7. Commands reference (no glob - general reference)
    generatedFiles.push({
      path: 'paradigm-commands.instructions.md',
      content: this.generateCommandsInstructions(),
    });

    // 8. Agent Hints (when to query CLI)
    generatedFiles.push({
      path: 'paradigm-agent-hints.instructions.md',
      content: this.generateAgentHintsInstructions(),
    });

    // 9. Commit conventions
    generatedFiles.push({
      path: 'paradigm-commits.instructions.md',
      content: this.generateCommitsInstructions(),
    });

    return generatedFiles;
  }

  /**
   * Core instructions - always applies (via copilot-instructions.md)
   */
  private generateCoreInstructions(projectName: string, config: ParadigmFiles['config']): string {
    const overview = generateOverview(config);
    
    return `# Copilot Instructions for ${projectName}

This file provides context for GitHub Copilot. Generated by Paradigm.

${overview}

${generateUpdateRules(config)}

---

## Additional Context

For detailed specifications, reference these files:

- \`.paradigm/specs/symbols.md\` - Complete symbol reference
- \`.paradigm/specs/logger.md\` - Logging specification
- \`.paradigm/specs/scan.md\` - Visual discovery protocol
- \`.paradigm/docs/\` - Documentation and troubleshooting
- \`.paradigm/prompts/\` - Pre-written task prompts

*Generated by Paradigm. Run \`paradigm sync copilot\` to regenerate.*
`;
  }

  /**
   * Symbol system instructions
   */
  private generateSymbolInstructions(config: ParadigmFiles['config']): string {
    return frontmatter('**/*.ts,**/*.tsx,**/*.js,**/*.jsx') +
      `# Paradigm Symbol System

${generateSymbolSystem(config)}
`;
  }

  /**
   * Logging instructions
   */
  private generateLoggingInstructions(config: ParadigmFiles['config']): string {
    return frontmatter('**/*.ts,**/*.tsx,**/*.js,**/*.jsx') +
      `# Paradigm Logging

${generateLoggingRules(config)}
`;
  }

  /**
   * Purpose file instructions
   */
  private generatePurposeInstructions(): string {
    return frontmatter('**/.purpose') +
      `# Purpose Files

Purpose files (\`.purpose\`) define the context for directories.

## Format

\`\`\`yaml
# Directory context
description: What this directory contains and why

# Components (# symbol) — all documented code units
components:
  component-name:
    description: What this component does
    tags: [feature]                # Classification via tag bank
    gates: [^gate1, ^gate2]       # Required gates
    signals: [!signal1]           # Events emitted
    used-by: [#other-component]
\`\`\`

## Symbol References (v2)

- Reference components: \`#component-name\`
- Reference flows: \`$flow-name\`
- Reference gates: \`^gate-name\`
- Reference signals: \`!signal-name\`
- Reference aspects: \`~aspect-name\`
`;
  }

  /**
   * Portal instructions
   */
  private generatePortalInstructions(): string {
    return frontmatter('**/portal.yaml') +
      `# Portal Configuration

Portal files (\`portal.yaml\`) define authorization topology.

## Format

\`\`\`yaml
version: "1.0"

gates:
  gate-name:
    description: What this gate protects
    locks:
      - id: lock-id
        description: Requirement description
        keys:
          - expression: "user.authenticated"
            description: User must be logged in
    prizes:
      - id: prize-id
        oneTime: true
        metadata:
          event: "gate_passed"

flows:
  flow-name:
    description: User journey
    gates: [gate1, gate2, gate3]
\`\`\`

## Portal Validation

Use the Portal Validator for authorization checks:

\`\`\`typescript
import { portal } from '@a-company/portal-sdk/validator';

const gate = portal.check('^gate-name')
  .requires('requirement description')
  .context({ userId, role });

if (!condition) {
  gate.deny('Reason for denial');
  return redirect('/unauthorized');
}

gate.allow('Access granted');
\`\`\`
`;
  }

  /**
   * Conventions instructions
   */
  private generateConventionsInstructions(config: ParadigmFiles['config']): string {
    return frontmatter('**/*.ts,**/*.tsx,**/*.js,**/*.jsx') +
      `# Paradigm Conventions

${generateConventions(config)}
`;
  }

  /**
   * Commands reference instructions
   */
  private generateCommandsInstructions(): string {
    // No frontmatter = requires manual selection or reference
    return `# Paradigm CLI Commands

${generateCommandsReference()}
`;
  }

  /**
   * Agent Hints instructions - when to query CLI
   */
  private generateAgentHintsInstructions(): string {
    // No frontmatter = always available for reference
    return `# Agent CLI Queries (Token-Efficient)

Instead of reading large context files, query Paradigm CLI on-demand for fresh, precise data.

## When to Query

| Before doing this... | Run this command |
|---------------------|------------------|
| Modifying a symbol | \`paradigm ripple #symbol --json\` |
| Debugging an error | \`paradigm echo ERROR_CODE --json\` |
| Starting a session | \`paradigm thread --json\` |
| Understanding relationships | \`paradigm constellation\` |
| Getting oriented | \`paradigm beacon --json\` |

## Query Patterns

### Before Changing Code

\`\`\`bash
# See what depends on what you're changing
paradigm ripple #checkout --json

# Output includes: upstream deps, downstream effects, flow membership
\`\`\`

### When Debugging

\`\`\`bash
# Look up error context
paradigm echo AUTH_REQUIRED --json

# Then check ripple effects of the related symbol
paradigm ripple ^authenticated --json
\`\`\`

### Starting Work

\`\`\`bash
# Check previous session context
paradigm thread --json

# Quick orientation
paradigm beacon --json
\`\`\`

### Querying Constellation

\`\`\`bash
# Get specific symbol
jq '.stars["#checkout"]' .paradigm/constellation.json

# Find what requires a gate
jq '[.stars | to_entries[] | select(.value.gates[]? == "^authenticated") | .key]' .paradigm/constellation.json

# List all flows
jq '.orbits | keys' .paradigm/constellation.json
\`\`\`

## Benefits

- **Fresh data**: Always current, not stale from file generation
- **Precise**: Only get the data you need
- **Token-efficient**: ~100 tokens per query vs ~2000 upfront
`;
  }
  /**
   * Commit conventions instructions
   */
  private generateCommitsInstructions(): string {
    // No frontmatter = always available for reference
    return `# Paradigm Commit Conventions

${generateCommitConvention()}
`;
  }
}

export const copilotAdapter = new CopilotAdapter();
