/**
 * GitHub Copilot IDE Adapter
 * Generates .github/copilot-instructions.md files
 */

import * as fs from 'fs';
import * as path from 'path';
import type { IDEAdapter, ParadigmFiles } from './types.js';
import {
  generateHeader,
  generateOverview,
  generateSymbolSystem,
  generateLoggingRules,
  generateScanProtocol,
  generateConventions,
  generateUpdateRules,
  generateCommandsReference,
  generateFooter,
} from './base.js';

export class CopilotAdapter implements IDEAdapter {
  readonly name = 'copilot';
  readonly displayName = 'GitHub Copilot';
  readonly outputPath = '.github/copilot-instructions.md';

  detect(rootDir: string): boolean {
    // Check for existing copilot instructions
    if (fs.existsSync(path.join(rootDir, '.github', 'copilot-instructions.md'))) {
      return true;
    }
    
    // Check for .github directory (common for GitHub-hosted projects)
    if (fs.existsSync(path.join(rootDir, '.github'))) {
      // Could be a GitHub project using Copilot
      return false; // Don't auto-detect, but allow explicit selection
    }
    
    return false;
  }

  generate(files: ParadigmFiles): string {
    const { config, projectName } = files;
    const sections: string[] = [];

    // Copilot-specific header
    sections.push(`# Copilot Instructions for ${projectName}`);
    sections.push('');
    sections.push('This file provides context for GitHub Copilot. Generated by Paradigm.');
    sections.push('');

    // Overview
    sections.push(generateOverview(config));

    // Symbol system
    sections.push(generateSymbolSystem(config));

    // Logging rules - extra emphasis for Copilot
    const loggingSection = generateLoggingRules(config);
    if (loggingSection) {
      sections.push(loggingSection);
    }

    // Scan protocol
    const scanSection = generateScanProtocol(config);
    if (scanSection) {
      sections.push(scanSection);
    }

    // Update rules
    sections.push(generateUpdateRules(config));

    // Conventions
    sections.push(generateConventions(config));

    // Commands reference
    sections.push(generateCommandsReference());

    // Copilot-specific footer
    sections.push('---');
    sections.push('');
    sections.push('## Additional Context');
    sections.push('');
    sections.push('For detailed specifications, reference these files:');
    sections.push('');
    sections.push('- `.paradigm/specs/symbols.md` - Complete symbol reference');
    sections.push('- `.paradigm/specs/logger.md` - Logging specification');
    sections.push('- `.paradigm/specs/scan.md` - Visual discovery protocol');
    sections.push('- `.paradigm/docs/` - Documentation and troubleshooting');
    sections.push('- `.paradigm/prompts/` - Pre-written task prompts');
    sections.push('');
    sections.push('*Generated by Paradigm. Run `paradigm sync copilot` to regenerate.*');

    return sections.filter(s => s.trim()).join('\n');
  }
}

export const copilotAdapter = new CopilotAdapter();
