/**
 * paradigm beacon - Generate quick-start orientation for AI agents
 * 
 * Creates .paradigm/beacon.md - a compact, agent-optimized summary
 * that provides immediate context without reading everything.
 */

import * as fs from 'fs';
import * as path from 'path';
import chalk from 'chalk';
import ora from 'ora';
import { log } from '../utils/logger.js';
import {
  aggregateFromDirectory,
  buildSymbolIndex,
  getSymbolsByType,
  getAllSymbols,
  getSymbolCounts,
  type SymbolEntry,
} from '@a-company/premise-core';

export interface BeaconOptions {
  refresh?: boolean;
  output?: string;
  quiet?: boolean;
  json?: boolean;
}

/**
 * JSON output structure for beacon
 */
interface BeaconJSON {
  project: string;
  generated: string;
  symbols: {
    features: Array<{ symbol: string; path: string; portals?: string[] }>;
    components: Array<{ symbol: string; path: string }>;
    portals: Array<{ symbol: string; description?: string }>;
  };
  landmarks: Array<{ path: string; description: string }>;
  pathways: Array<{ name: string; path: string }>;
  stats: {
    features: number;
    components: number;
    portals: number;
    total: number;
  };
}

/**
 * Group symbols by their directory
 */
function groupByDirectory(symbols: SymbolEntry[]): Map<string, SymbolEntry[]> {
  const groups = new Map<string, SymbolEntry[]>();
  
  for (const symbol of symbols) {
    const dir = path.dirname(symbol.filePath);
    if (!groups.has(dir)) {
      groups.set(dir, []);
    }
    groups.get(dir)!.push(symbol);
  }
  
  return groups;
}

/**
 * Find key files in the project
 */
function findLandmarks(rootDir: string): { path: string; description: string }[] {
  const landmarks: { path: string; description: string }[] = [];
  
  // Common important files to look for
  const importantFiles = [
    { pattern: 'portal.yaml', desc: 'Authorization topology' },
    { pattern: 'src/lib/api.ts', desc: 'API utilities' },
    { pattern: 'src/lib/api.js', desc: 'API utilities' },
    { pattern: 'src/utils/api.ts', desc: 'API utilities' },
    { pattern: 'src/hooks/useAuth.ts', desc: 'Auth hook' },
    { pattern: 'src/hooks/useAuth.tsx', desc: 'Auth hook' },
    { pattern: 'src/context/AuthContext.tsx', desc: 'Auth context' },
    { pattern: 'src/store/index.ts', desc: 'State store' },
    { pattern: 'src/types/index.ts', desc: 'Type definitions' },
    { pattern: 'src/types.ts', desc: 'Type definitions' },
    { pattern: '.paradigm/config.yaml', desc: 'Paradigm config' },
    { pattern: 'tsconfig.json', desc: 'TypeScript config' },
    { pattern: 'package.json', desc: 'Package manifest' },
  ];
  
  for (const { pattern, desc } of importantFiles) {
    const fullPath = path.join(rootDir, pattern);
    if (fs.existsSync(fullPath)) {
      landmarks.push({ path: pattern, description: desc });
    }
  }
  
  return landmarks.slice(0, 8); // Limit to 8 landmarks
}

/**
 * Find available prompts
 */
function findPathways(rootDir: string): { name: string; path: string }[] {
  const promptsDir = path.join(rootDir, '.paradigm', 'prompts');
  const pathways: { name: string; path: string }[] = [];
  
  if (fs.existsSync(promptsDir)) {
    const files = fs.readdirSync(promptsDir).filter(f => f.endsWith('.md'));
    for (const file of files) {
      const name = file.replace('.md', '').replace(/-/g, ' ');
      pathways.push({
        name: name.charAt(0).toUpperCase() + name.slice(1),
        path: `.paradigm/prompts/${file}`,
      });
    }
  }
  
  return pathways.slice(0, 6); // Limit to 6 pathways
}

/**
 * Generate the beacon markdown content
 */
function generateBeacon(
  projectName: string,
  symbols: SymbolEntry[],
  landmarks: { path: string; description: string }[],
  pathways: { name: string; path: string }[],
  rootDir: string
): string {
  const lines: string[] = [];
  
  // Header
  lines.push(`# Beacon - ${projectName}`);
  lines.push('');
  lines.push('> Quick-start orientation for AI agents. Generated by Paradigm.');
  lines.push('');
  
  // Constellation (Symbol Map)
  lines.push('## Constellation (Symbol Map)');
  lines.push('');
  lines.push('```');
  
  // Group features by what they require
  const features = symbols.filter(s => s.type === 'feature');
  const components = symbols.filter(s => s.type === 'component');
  const gates = symbols.filter(s => s.type === 'gate');
  
  // Show features with their gates
  for (const feature of features.slice(0, 10)) {
    const featureGates = feature.references.filter(r => r.startsWith('^'));
    const featureComponents = feature.references.filter(r => r.startsWith('#'));
    
    let line = `${feature.symbol.padEnd(20)} → ${path.dirname(feature.filePath).padEnd(25)}`;
    if (featureGates.length > 0) {
      line += ` → ${featureGates.join(', ')}`;
    }
    lines.push(line);
  }
  
  if (features.length > 10) {
    lines.push(`... and ${features.length - 10} more features`);
  }
  
  // Show key components
  if (components.length > 0) {
    lines.push('');
    for (const component of components.slice(0, 5)) {
      lines.push(`${component.symbol.padEnd(20)} → ${path.dirname(component.filePath)}`);
    }
    if (components.length > 5) {
      lines.push(`... and ${components.length - 5} more components`);
    }
  }
  
  lines.push('```');
  lines.push('');
  
  // Gates summary
  if (gates.length > 0) {
    lines.push('## Portals (Authorization Gates)');
    lines.push('');
    for (const gate of gates.slice(0, 6)) {
      const desc = gate.description ? ` - ${gate.description}` : '';
      lines.push(`- \`${gate.symbol}\`${desc}`);
    }
    if (gates.length > 6) {
      lines.push(`- ... and ${gates.length - 6} more portals`);
    }
    lines.push('');
  }
  
  // Landmarks (Key Files)
  if (landmarks.length > 0) {
    lines.push('## Landmarks (Key Files)');
    lines.push('');
    for (const landmark of landmarks) {
      lines.push(`- \`${landmark.path}\` - ${landmark.description}`);
    }
    lines.push('');
  }
  
  // Pathways (Common Tasks)
  if (pathways.length > 0) {
    lines.push('## Pathways (Common Tasks)');
    lines.push('');
    for (const pathway of pathways) {
      lines.push(`- "${pathway.name}" → \`${pathway.path}\``);
    }
    lines.push('');
  }
  
  // Quick Reference
  lines.push('## Symbol Quick Reference');
  lines.push('');
  lines.push('| Symbol | Type | Meaning |');
  lines.push('|--------|------|---------|');
  lines.push('| `@` | Feature | User-facing capability |');
  lines.push('| `#` | Component | Reusable code unit |');
  lines.push('| `^` | Portal | Authorization gate |');
  lines.push('| `!` | Signal | Event or side effect |');
  lines.push('| `$` | Flow | Multi-step process |');
  lines.push('| `%` | State | Data condition |');
  lines.push('| `~` | Deprecated | Marked for removal |');
  lines.push('| `?` | Idea | Future possibility |');
  lines.push('');
  
  // For More Context
  lines.push('## For More Context');
  lines.push('');
  lines.push('- Full symbol graph: `.paradigm/constellation.json`');
  lines.push('- Detailed context: `.paradigm/specs/` for detailed specifications');
  lines.push('- Session history: `.paradigm/thread.md` (if available)');
  lines.push('- Error mapping: `.paradigm/echoes.yaml` (if available)');
  lines.push('');
  
  // Footer
  lines.push('---');
  lines.push(`*Generated: ${new Date().toISOString().split('T')[0]}*`);
  lines.push(`*Run \`paradigm beacon --refresh\` to update*`);
  
  return lines.join('\n');
}

export async function beaconCommand(targetPath?: string, options: BeaconOptions = {}) {
  const cwd = process.cwd();
  const absolutePath = targetPath ? path.resolve(cwd, targetPath) : cwd;
  const projectName = path.basename(absolutePath);

  // For JSON output, skip all UI
  const showUI = !options.json && !options.quiet;

  if (showUI) {
    console.log(chalk.blue('\n🔦 Generating Beacon...\n'));
  }

  const spinner = options.json ? null : ora('Scanning project...').start();
  const tracker = log.command('beacon').start('Generating beacon', { project: projectName });

  try {
    // Check if beacon exists and not refreshing (skip for JSON)
    const paradigmDir = path.join(absolutePath, '.paradigm');
    const beaconPath = options.output || path.join(paradigmDir, 'beacon.md');
    
    if (!options.json && fs.existsSync(beaconPath) && !options.refresh) {
      spinner?.info('Beacon already exists');
      if (showUI) {
        console.log(chalk.gray(`  Use --refresh to regenerate\n`));
        console.log(chalk.gray(`  Path: ${beaconPath}\n`));
        
        // Show existing beacon content summary
        const content = fs.readFileSync(beaconPath, 'utf8');
        const lines = content.split('\n').slice(0, 15);
        console.log(chalk.white('Current Beacon (preview):'));
        console.log(chalk.gray('─'.repeat(40)));
        for (const line of lines) {
          console.log(chalk.gray(`  ${line}`));
        }
        console.log(chalk.gray('  ...'));
        console.log('');
      }
      return;
    }

    // Aggregate symbols
    const result = await aggregateFromDirectory(absolutePath);
    const index = buildSymbolIndex(result);
    const symbols = getAllSymbols(index);

    spinner && (spinner.text = 'Finding landmarks...');
    const landmarks = findLandmarks(absolutePath);
    
    spinner && (spinner.text = 'Finding pathways...');
    const pathways = findPathways(absolutePath);

    // JSON output mode
    if (options.json) {
      const features = symbols.filter(s => s.type === 'feature');
      const components = symbols.filter(s => s.type === 'component');
      const gates = symbols.filter(s => s.type === 'gate');
      const counts = getSymbolCounts(index);
      
      const jsonOutput: BeaconJSON = {
        project: projectName,
        generated: new Date().toISOString(),
        symbols: {
          features: features.map(f => ({
            symbol: f.symbol,
            path: path.dirname(f.filePath),
            portals: f.references.filter(r => r.startsWith('^')).length > 0 
              ? f.references.filter(r => r.startsWith('^'))
              : undefined,
          })),
          components: components.map(c => ({
            symbol: c.symbol,
            path: path.dirname(c.filePath),
          })),
          portals: gates.map(g => ({
            symbol: g.symbol,
            description: g.description,
          })),
        },
        landmarks,
        pathways,
        stats: {
          features: counts.feature,
          components: counts.component,
          portals: counts.gate,
          total: Object.values(counts).reduce((a, b) => a + b, 0),
        },
      };
      
      console.log(JSON.stringify(jsonOutput, null, 2));
      return jsonOutput;
    }

    spinner && (spinner.text = 'Generating beacon...');
    
    // Generate beacon content
    const beaconContent = generateBeacon(
      projectName,
      symbols,
      landmarks,
      pathways,
      absolutePath
    );

    // Ensure .paradigm directory exists
    if (!fs.existsSync(paradigmDir)) {
      fs.mkdirSync(paradigmDir, { recursive: true });
    }

    // Write beacon
    fs.writeFileSync(beaconPath, beaconContent, 'utf8');
    log.component('beacon-file').success('Beacon file written', { path: beaconPath });

    spinner.succeed('Beacon generated');
    tracker.success('Beacon generated', { path: beaconPath, symbols: symbols.length });

    if (!options.quiet) {
      const counts = getSymbolCounts(index);
      
      console.log(chalk.white('\nBeacon Contents'));
      console.log(chalk.gray('─'.repeat(40)));
      console.log(`  Features:    ${chalk.blue(counts.feature.toString())}`);
      console.log(`  Components:  ${chalk.green(counts.component.toString())}`);
      console.log(`  Portals:     ${chalk.red(counts.gate.toString())}`);
      console.log(`  Landmarks:   ${chalk.cyan(landmarks.length.toString())}`);
      console.log(`  Pathways:    ${chalk.yellow(pathways.length.toString())}`);
      
      console.log(chalk.gray(`\n  Output: ${beaconPath}\n`));
      
      // Tip
      console.log(chalk.white('Tip'));
      console.log(chalk.gray('─'.repeat(40)));
      console.log(chalk.gray('  AI agents should read beacon.md first for quick orientation.'));
      console.log(chalk.gray('  Then constellation.json for detailed relationships.\n'));
    }

  } catch (error) {
    spinner?.fail('Failed to generate beacon');
    tracker.error('Beacon generation failed', { error: (error as Error).message });
    console.log(chalk.red(`Error: ${(error as Error).message}\n`));
    process.exit(1);
  }
}
