/**
 * Protocol Loader - Reads/writes protocols from .paradigm/protocols/
 *
 * Storage layout:
 *   .paradigm/protocols/
 *     index.yaml              # Auto-generated by reindex (summary + health)
 *     add-view.protocol       # One file per protocol
 *     add-api-route.protocol
 */

import * as fs from 'fs';
import * as path from 'path';
import * as yaml from 'js-yaml';

const PROTOCOLS_DIR = '.paradigm/protocols';
const INDEX_FILE = 'index.yaml';

// ────────────────────────────────────────────────────────
// Types
// ────────────────────────────────────────────────────────

export interface ProtocolStep {
  action: 'create' | 'modify' | 'run' | 'verify';
  target?: string;
  template_from?: string;
  reference?: string;
  command?: string;
  notes?: string;
}

export interface Protocol {
  id: string;
  name: string;
  description: string;
  trigger: string[];
  tags: string[];
  symbols: string[];
  exemplar?: string;
  steps: ProtocolStep[];
  recorded_from?: string;
  recorded_at: string;
  last_verified: string;
  verified_by?: string;
  status: 'current' | 'stale' | 'broken';
}

export interface ProtocolIndex {
  version: string;
  generated: string;
  protocols: ProtocolIndexEntry[];
  health: {
    total: number;
    current: number;
    stale: number;
    broken: number;
  };
}

export interface ProtocolIndexEntry {
  id: string;
  name: string;
  status: 'current' | 'stale' | 'broken';
  last_verified: string;
  trigger: string[];
  tags: string[];
}

export interface ProtocolSearchResult {
  protocol: Protocol;
  score: number;
}

// ────────────────────────────────────────────────────────
// Read operations
// ────────────────────────────────────────────────────────

/**
 * Load all protocols from .paradigm/protocols/
 */
export async function loadProtocols(rootDir: string): Promise<Protocol[]> {
  const protocolsDir = path.join(rootDir, PROTOCOLS_DIR);
  if (!fs.existsSync(protocolsDir)) {
    return [];
  }

  const files = fs.readdirSync(protocolsDir)
    .filter(f => f.endsWith('.protocol'))
    .sort();

  const protocols: Protocol[] = [];
  for (const file of files) {
    try {
      const content = fs.readFileSync(path.join(protocolsDir, file), 'utf8');
      const protocol = yaml.load(content) as Protocol;
      if (protocol?.id && protocol?.name) {
        protocols.push(protocol);
      }
    } catch {
      // Skip malformed files
    }
  }

  return protocols;
}

/**
 * Load a single protocol by ID
 */
export async function loadProtocol(rootDir: string, id: string): Promise<Protocol | null> {
  const slug = id.replace(/^P-/, '');
  const filePath = path.join(rootDir, PROTOCOLS_DIR, `${slug}.protocol`);

  if (fs.existsSync(filePath)) {
    try {
      const content = fs.readFileSync(filePath, 'utf8');
      return yaml.load(content) as Protocol;
    } catch {
      return null;
    }
  }

  // Fallback: scan all files
  const protocols = await loadProtocols(rootDir);
  return protocols.find(p => p.id === id) || null;
}

/**
 * Load the protocol index (auto-generated by reindex)
 */
export async function loadProtocolIndex(rootDir: string): Promise<ProtocolIndex | null> {
  const indexPath = path.join(rootDir, PROTOCOLS_DIR, INDEX_FILE);
  if (!fs.existsSync(indexPath)) {
    return null;
  }

  try {
    const content = fs.readFileSync(indexPath, 'utf8');
    return yaml.load(content) as ProtocolIndex;
  } catch {
    return null;
  }
}

// ────────────────────────────────────────────────────────
// Search
// ────────────────────────────────────────────────────────

/**
 * Fuzzy search protocols by task description.
 *
 * Scoring:
 *   trigger phrases — weight 3
 *   tags           — weight 2
 *   name + desc    — weight 1
 *   step notes     — weight 0.5
 */
export async function searchProtocols(
  rootDir: string,
  task: string,
  limit = 3,
): Promise<ProtocolSearchResult[]> {
  const protocols = await loadProtocols(rootDir);
  if (protocols.length === 0) return [];

  const keywords = tokenize(task);
  if (keywords.length === 0) return [];

  const scored: ProtocolSearchResult[] = [];

  for (const protocol of protocols) {
    let score = 0;

    // trigger phrases — weight 3
    for (const trigger of protocol.trigger) {
      const triggerLower = trigger.toLowerCase();
      for (const kw of keywords) {
        if (triggerLower.includes(kw)) {
          score += 3;
        }
      }
    }

    // tags — weight 2
    for (const tag of protocol.tags) {
      const tagLower = tag.toLowerCase();
      for (const kw of keywords) {
        if (tagLower.includes(kw) || kw.includes(tagLower)) {
          score += 2;
        }
      }
    }

    // name + description — weight 1
    const nameLower = protocol.name.toLowerCase();
    const descLower = protocol.description.toLowerCase();
    for (const kw of keywords) {
      if (nameLower.includes(kw)) score += 1;
      if (descLower.includes(kw)) score += 1;
    }

    // step notes — weight 0.5
    for (const step of protocol.steps) {
      if (step.notes) {
        const notesLower = step.notes.toLowerCase();
        for (const kw of keywords) {
          if (notesLower.includes(kw)) score += 0.5;
        }
      }
    }

    if (score > 0) {
      scored.push({ protocol, score });
    }
  }

  scored.sort((a, b) => b.score - a.score);
  return scored.slice(0, limit);
}

// ────────────────────────────────────────────────────────
// Write operations
// ────────────────────────────────────────────────────────

/**
 * Record a new protocol
 */
export async function recordProtocol(
  rootDir: string,
  protocol: Omit<Protocol, 'id' | 'recorded_at' | 'last_verified' | 'status'>,
): Promise<string> {
  const protocolsDir = path.join(rootDir, PROTOCOLS_DIR);
  if (!fs.existsSync(protocolsDir)) {
    fs.mkdirSync(protocolsDir, { recursive: true });
  }

  const slug = slugify(protocol.name);
  const id = `P-${slug}`;
  const now = new Date().toISOString();

  const full: Protocol = {
    id,
    name: protocol.name,
    description: protocol.description,
    trigger: protocol.trigger,
    tags: protocol.tags,
    symbols: protocol.symbols || [],
    exemplar: protocol.exemplar,
    steps: protocol.steps,
    recorded_from: protocol.recorded_from,
    recorded_at: now,
    last_verified: now,
    verified_by: protocol.verified_by || 'claude-opus-4-6',
    status: 'current',
  };

  const filePath = path.join(protocolsDir, `${slug}.protocol`);
  fs.writeFileSync(filePath, yaml.dump(full, { lineWidth: -1, noRefs: true }), 'utf8');

  return id;
}

/**
 * Update an existing protocol
 */
export async function updateProtocol(
  rootDir: string,
  id: string,
  partial: Partial<Omit<Protocol, 'id'>>,
  refresh = false,
): Promise<boolean> {
  const protocol = await loadProtocol(rootDir, id);
  if (!protocol) return false;

  // Merge fields
  if (partial.name !== undefined) protocol.name = partial.name;
  if (partial.description !== undefined) protocol.description = partial.description;
  if (partial.trigger !== undefined) protocol.trigger = partial.trigger;
  if (partial.tags !== undefined) protocol.tags = partial.tags;
  if (partial.symbols !== undefined) protocol.symbols = partial.symbols;
  if (partial.exemplar !== undefined) protocol.exemplar = partial.exemplar;
  if (partial.steps !== undefined) protocol.steps = partial.steps;
  if (partial.status !== undefined) protocol.status = partial.status;
  if (partial.verified_by !== undefined) protocol.verified_by = partial.verified_by;

  if (refresh) {
    protocol.last_verified = new Date().toISOString();
    protocol.verified_by = partial.verified_by || 'claude-opus-4-6';
  }

  const slug = id.replace(/^P-/, '');
  const filePath = path.join(rootDir, PROTOCOLS_DIR, `${slug}.protocol`);
  fs.writeFileSync(filePath, yaml.dump(protocol, { lineWidth: -1, noRefs: true }), 'utf8');
  return true;
}

// ────────────────────────────────────────────────────────
// Validation & Index Rebuild
// ────────────────────────────────────────────────────────

/**
 * Validate a protocol: check referenced files exist, exemplar hasn't drifted.
 * Updates the protocol's status field.
 */
export function validateProtocol(rootDir: string, protocol: Protocol): {
  status: 'current' | 'stale' | 'broken';
  issues: string[];
} {
  const issues: string[] = [];
  let status: Protocol['status'] = 'current';

  // Check exemplar exists
  if (protocol.exemplar) {
    const exemplarPath = path.join(rootDir, protocol.exemplar);
    if (!fs.existsSync(exemplarPath)) {
      issues.push(`Exemplar missing: ${protocol.exemplar}`);
      status = 'broken';
    } else {
      // Check if exemplar was modified after last_verified
      const stat = fs.statSync(exemplarPath);
      if (stat.mtime.toISOString() > protocol.last_verified) {
        issues.push(`Exemplar modified since last verified: ${protocol.exemplar}`);
        if (status !== 'broken') status = 'stale';
      }
    }
  }

  // Check step targets/template_from exist
  for (const step of protocol.steps) {
    if (step.template_from) {
      const templatePath = path.join(rootDir, step.template_from);
      if (!fs.existsSync(templatePath)) {
        issues.push(`Template file missing: ${step.template_from}`);
        status = 'broken';
      }
    }

    if (step.action === 'modify' && step.target) {
      const targetPath = path.join(rootDir, step.target);
      // Only check non-placeholder targets
      if (!step.target.includes('{') && !fs.existsSync(targetPath)) {
        issues.push(`Modify target missing: ${step.target}`);
        status = 'broken';
      }
    }
  }

  return { status, issues };
}

/**
 * Validate all protocols and rebuild the index.yaml file.
 * Called during paradigm_reindex.
 */
export async function rebuildProtocolIndex(rootDir: string): Promise<ProtocolIndex> {
  const protocols = await loadProtocols(rootDir);
  const entries: ProtocolIndexEntry[] = [];
  let current = 0;
  let stale = 0;
  let broken = 0;

  for (const protocol of protocols) {
    const validation = validateProtocol(rootDir, protocol);

    // Update status in-place if changed
    if (protocol.status !== validation.status) {
      protocol.status = validation.status;
      const slug = protocol.id.replace(/^P-/, '');
      const filePath = path.join(rootDir, PROTOCOLS_DIR, `${slug}.protocol`);
      if (fs.existsSync(filePath)) {
        fs.writeFileSync(filePath, yaml.dump(protocol, { lineWidth: -1, noRefs: true }), 'utf8');
      }
    }

    switch (validation.status) {
      case 'current': current++; break;
      case 'stale': stale++; break;
      case 'broken': broken++; break;
    }

    entries.push({
      id: protocol.id,
      name: protocol.name,
      status: validation.status,
      last_verified: protocol.last_verified,
      trigger: protocol.trigger,
      tags: protocol.tags,
    });
  }

  const index: ProtocolIndex = {
    version: '1.0',
    generated: new Date().toISOString(),
    protocols: entries,
    health: {
      total: protocols.length,
      current,
      stale,
      broken,
    },
  };

  const protocolsDir = path.join(rootDir, PROTOCOLS_DIR);
  if (protocols.length > 0) {
    if (!fs.existsSync(protocolsDir)) {
      fs.mkdirSync(protocolsDir, { recursive: true });
    }
    const indexPath = path.join(protocolsDir, INDEX_FILE);
    fs.writeFileSync(indexPath, yaml.dump(index, { lineWidth: -1, noRefs: true }), 'utf8');
  }

  return index;
}

// ────────────────────────────────────────────────────────
// Protocol Suggestion (for lore integration)
// ────────────────────────────────────────────────────────

export interface ProtocolSuggestion {
  hint: string;
  draft: {
    name: string;
    exemplar?: string;
    steps: Array<{ action: string; target: string }>;
  };
}

/**
 * Detect if a lore session's work follows a "protocol-worthy" pattern.
 *
 * Heuristic:
 * - Session created 2+ new files in a directory with similar existing files
 * - OR modified the same "registration" files (App.tsx, index.ts, etc.)
 */
export function detectProtocolSuggestion(
  rootDir: string,
  filesCreated: string[],
  filesModified: string[],
): ProtocolSuggestion | null {
  if (!filesCreated || filesCreated.length < 2) return null;

  // Group created files by directory
  const dirGroups: Record<string, string[]> = {};
  for (const file of filesCreated) {
    const dir = path.dirname(file);
    if (!dirGroups[dir]) dirGroups[dir] = [];
    dirGroups[dir].push(file);
  }

  // Find directories where 2+ files were created and similar files already exist
  for (const [dir, created] of Object.entries(dirGroups)) {
    if (created.length < 2) continue;

    const absDir = path.join(rootDir, dir);
    if (!fs.existsSync(absDir)) continue;

    const existing = fs.readdirSync(absDir).filter(f => {
      const ext = path.extname(f);
      return ['.ts', '.tsx', '.js', '.jsx', '.rs', '.py'].includes(ext);
    });

    // If directory already had files before we created ours, it's a pattern
    const preExisting = existing.filter(f => !created.some(c => path.basename(c) === f));
    if (preExisting.length > 0) {
      const exemplar = path.join(dir, preExisting[0]);
      const steps = [
        ...created.map(f => ({ action: 'create', target: f })),
        ...filesModified.map(f => ({ action: 'modify', target: f })),
      ];

      return {
        hint: `This session created ${created.length} new files in ${dir}/ following existing patterns. Consider recording a protocol.`,
        draft: {
          name: `Add a ${path.basename(dir).replace(/s$/, '')}`,
          exemplar,
          steps,
        },
      };
    }
  }

  return null;
}

// ────────────────────────────────────────────────────────
// Internal helpers
// ────────────────────────────────────────────────────────

function tokenize(text: string): string[] {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, ' ')
    .split(/\s+/)
    .filter(w => w.length > 1)
    .filter(w => !STOP_WORDS.has(w));
}

const STOP_WORDS = new Set([
  'a', 'an', 'the', 'is', 'are', 'was', 'were', 'be', 'been',
  'to', 'of', 'in', 'for', 'on', 'with', 'at', 'by', 'from',
  'it', 'this', 'that', 'and', 'or', 'but', 'if', 'then',
  'so', 'as', 'do', 'does', 'did', 'will', 'would', 'can',
  'could', 'should', 'may', 'might', 'must', 'shall',
  'i', 'me', 'my', 'we', 'our', 'you', 'your', 'he', 'she',
  'how', 'what', 'when', 'where', 'which', 'who', 'whom',
]);

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}
