/**
 * Scenario Loader — The Classroom scenario bank artifact (TD-2026-06-19-007).
 *
 * The scenario bank is the "no scenario, no assessment" substrate: every
 * assessment must author a BREAKING test-case scenario. Scenarios arrive from
 * three origins — `field-failure` (the field generates the probe a same-family
 * peer structurally could not — the kill-shot answer), `poison-pill` (planted
 * known-wrongs; the honesty meter), and `authored` (a human/peer assessor).
 *
 * Storage layout:
 *   .paradigm/curriculum/scenarios/
 *     index.yaml             # Auto-generated by reindex (summary)
 *     <id>.scenario          # One file per scenario (YAML)
 *
 * Mirrors the protocol-loader machinery: one file per scenario, an index rebuild
 * hooked into paradigm_reindex, and append-only outcome history.
 */

import * as fs from 'fs';
import * as path from 'path';
import * as yaml from 'js-yaml';

const SCENARIOS_DIR = '.paradigm/curriculum/scenarios';
const INDEX_FILE = 'index.yaml';

// ────────────────────────────────────────────────────────
// Types
// ────────────────────────────────────────────────────────

export type ScenarioOrigin = 'field-failure' | 'poison-pill' | 'authored';
export type ScenarioStatus = 'active' | 'retired';

export interface ScenarioProbe {
  agent: string;
  /** The learning (notebook entry id) this probe targets. */
  learning_ref: string;
  /** The claim the probe tests (what the learning asserts). */
  claim: string;
}

export interface ScenarioOutcome {
  /** Term id this outcome was assessed in. */
  term: string;
  agent: string;
  result: 'survived' | 'broke';
  assessor: string;
  human_confirmed: boolean;
  at: string;
}

export interface Scenario {
  id: string;
  /** The breaking test-case prose. */
  scenario: string;
  probes: ScenarioProbe[];
  origin: ScenarioOrigin;
  /** Provenance: the field-failure id / poison-pill id / lore id this came from. */
  origin_ref?: string;
  expected: { must: 'survive' | 'reject' };
  outcome_history: ScenarioOutcome[];
  /** Count of times a probe here broke again — the repeat-failure signal. */
  repeat_failures: number;
  status: ScenarioStatus;
}

export interface ScenarioIndexEntry {
  id: string;
  origin: ScenarioOrigin;
  status: ScenarioStatus;
  agents: string[];
  repeat_failures: number;
}

export interface ScenarioIndex {
  version: string;
  generated: string;
  scenarios: ScenarioIndexEntry[];
  health: {
    total: number;
    active: number;
    retired: number;
    byOrigin: Record<ScenarioOrigin, number>;
  };
}

// ────────────────────────────────────────────────────────
// Read operations
// ────────────────────────────────────────────────────────

/** Load every scenario from the bank. */
export async function loadScenarios(rootDir: string): Promise<Scenario[]> {
  const dir = path.join(rootDir, SCENARIOS_DIR);
  if (!fs.existsSync(dir)) return [];

  const files = fs.readdirSync(dir)
    .filter(f => f.endsWith('.scenario'))
    .sort();

  const scenarios: Scenario[] = [];
  for (const file of files) {
    try {
      const content = fs.readFileSync(path.join(dir, file), 'utf8');
      const scenario = yaml.load(content) as Scenario;
      if (scenario?.id) {
        scenarios.push(scenario);
      }
    } catch {
      // Skip malformed files
    }
  }

  return scenarios;
}

/** Load a single scenario by id. */
export async function loadScenario(rootDir: string, id: string): Promise<Scenario | null> {
  const filePath = path.join(rootDir, SCENARIOS_DIR, `${id}.scenario`);
  if (fs.existsSync(filePath)) {
    try {
      return yaml.load(fs.readFileSync(filePath, 'utf8')) as Scenario;
    } catch {
      return null;
    }
  }
  const all = await loadScenarios(rootDir);
  return all.find(s => s.id === id) || null;
}

/** Load scenarios whose probes target a given agent. */
export async function loadScenariosForAgent(
  rootDir: string,
  agentId: string,
): Promise<Scenario[]> {
  const all = await loadScenarios(rootDir);
  return all.filter(s => s.probes.some(p => p.agent === agentId));
}

/** Load the scenario index (auto-generated by reindex). */
export async function loadScenarioIndex(rootDir: string): Promise<ScenarioIndex | null> {
  const indexPath = path.join(rootDir, SCENARIOS_DIR, INDEX_FILE);
  if (!fs.existsSync(indexPath)) return null;
  try {
    return yaml.load(fs.readFileSync(indexPath, 'utf8')) as ScenarioIndex;
  } catch {
    return null;
  }
}

// ────────────────────────────────────────────────────────
// Write operations
// ────────────────────────────────────────────────────────

/**
 * Record a new scenario. The caller supplies a stable id (the converter passes
 * a field-failure-derived id so the dedupe is structural). If a scenario with
 * the same id already exists it is NOT overwritten — recordScenario is a safe
 * "create if absent". Returns the scenario id.
 */
export async function recordScenario(
  rootDir: string,
  scenario: Omit<Scenario, 'outcome_history' | 'repeat_failures' | 'status'> & {
    outcome_history?: ScenarioOutcome[];
    repeat_failures?: number;
    status?: ScenarioStatus;
  },
): Promise<string> {
  const dir = path.join(rootDir, SCENARIOS_DIR);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  const filePath = path.join(dir, `${scenario.id}.scenario`);
  if (fs.existsSync(filePath)) {
    // Create-if-absent: existing scenario wins (preserves outcome history).
    return scenario.id;
  }

  const full: Scenario = {
    id: scenario.id,
    scenario: scenario.scenario,
    probes: scenario.probes || [],
    origin: scenario.origin,
    origin_ref: scenario.origin_ref,
    expected: scenario.expected,
    outcome_history: scenario.outcome_history || [],
    repeat_failures: scenario.repeat_failures ?? 0,
    status: scenario.status || 'active',
  };

  fs.writeFileSync(filePath, yaml.dump(full, { lineWidth: -1, noRefs: true }), 'utf8');
  return scenario.id;
}

/** True if a scenario already exists for the given origin_ref (dedupe guard). */
export async function scenarioExistsForOriginRef(
  rootDir: string,
  originRef: string,
): Promise<boolean> {
  const all = await loadScenarios(rootDir);
  return all.some(s => s.origin_ref === originRef);
}

/**
 * Append an outcome to a scenario's history. Bumps `repeat_failures` when the
 * result is `broke` (the repeat-failure-rate signal). Rewrites the file in place.
 * Returns false if the scenario does not exist.
 */
export async function appendScenarioOutcome(
  rootDir: string,
  scenarioId: string,
  outcome: ScenarioOutcome,
): Promise<boolean> {
  const filePath = path.join(rootDir, SCENARIOS_DIR, `${scenarioId}.scenario`);
  if (!fs.existsSync(filePath)) return false;

  let scenario: Scenario;
  try {
    scenario = yaml.load(fs.readFileSync(filePath, 'utf8')) as Scenario;
  } catch {
    return false;
  }
  if (!scenario?.id) return false;

  scenario.outcome_history = scenario.outcome_history || [];
  scenario.outcome_history.push(outcome);
  if (outcome.result === 'broke') {
    scenario.repeat_failures = (scenario.repeat_failures ?? 0) + 1;
  }

  fs.writeFileSync(filePath, yaml.dump(scenario, { lineWidth: -1, noRefs: true }), 'utf8');
  return true;
}

// ────────────────────────────────────────────────────────
// Index Rebuild
// ────────────────────────────────────────────────────────

/** Rebuild scenarios/index.yaml. Called during paradigm_reindex. */
export async function rebuildScenarioIndex(rootDir: string): Promise<ScenarioIndex> {
  const scenarios = await loadScenarios(rootDir);
  const entries: ScenarioIndexEntry[] = [];
  let active = 0;
  let retired = 0;
  const byOrigin: Record<ScenarioOrigin, number> = {
    'field-failure': 0,
    'poison-pill': 0,
    authored: 0,
  };

  for (const scenario of scenarios) {
    if (scenario.status === 'retired') retired++;
    else active++;
    byOrigin[scenario.origin] = (byOrigin[scenario.origin] ?? 0) + 1;

    entries.push({
      id: scenario.id,
      origin: scenario.origin,
      status: scenario.status,
      agents: Array.from(new Set(scenario.probes.map(p => p.agent))),
      repeat_failures: scenario.repeat_failures ?? 0,
    });
  }

  const index: ScenarioIndex = {
    version: '1.0',
    generated: new Date().toISOString(),
    scenarios: entries,
    health: { total: scenarios.length, active, retired, byOrigin },
  };

  const dir = path.join(rootDir, SCENARIOS_DIR);
  if (scenarios.length > 0) {
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(
      path.join(dir, INDEX_FILE),
      yaml.dump(index, { lineWidth: -1, noRefs: true }),
      'utf8',
    );
  }

  return index;
}

/**
 * Derive a deterministic scenario id from a field-failure id. Used by the
 * field-failure → scenario converter so the dedupe is structural (one scenario
 * per unique failure).
 */
export function scenarioIdForFailure(failureId: string): string {
  return `SC-${failureId}`;
}

// ────────────────────────────────────────────────────────
// Sync converter surface (for the field-failure reducer)
// ────────────────────────────────────────────────────────

/**
 * Sync "create scenario if none exists for this origin_ref". The field-failure
 * reducer is a synchronous postflight pass, so the field-failure → scenario
 * converter needs a sync seam. Dedupe is on `origin_ref` (one scenario per
 * unique failure) so a second postflight pass over the same break does NOT spam
 * the bank.
 *
 * @returns the scenario id if created, or null if a scenario already covers this
 *   origin_ref (already converted).
 */
export function recordScenarioFromFailureSync(
  rootDir: string,
  scenario: Omit<Scenario, 'outcome_history' | 'repeat_failures' | 'status'>,
): string | null {
  const dir = path.join(rootDir, SCENARIOS_DIR);

  // Dedupe on origin_ref by scanning existing scenario files.
  if (scenario.origin_ref && fs.existsSync(dir)) {
    for (const file of fs.readdirSync(dir)) {
      if (!file.endsWith('.scenario')) continue;
      try {
        const existing = yaml.load(
          fs.readFileSync(path.join(dir, file), 'utf8'),
        ) as { origin_ref?: string };
        if (existing?.origin_ref === scenario.origin_ref) return null;
      } catch {
        // skip unparseable
      }
    }
  }

  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  const filePath = path.join(dir, `${scenario.id}.scenario`);
  if (fs.existsSync(filePath)) return null; // id collision = already present

  const full: Scenario = {
    id: scenario.id,
    scenario: scenario.scenario,
    probes: scenario.probes || [],
    origin: scenario.origin,
    origin_ref: scenario.origin_ref,
    expected: scenario.expected,
    outcome_history: [],
    repeat_failures: 0,
    status: 'active',
  };
  fs.writeFileSync(filePath, yaml.dump(full, { lineWidth: -1, noRefs: true }), 'utf8');
  return scenario.id;
}
