/**
 * Syllabus Loader — The Classroom per-agent curriculum artifact (TD-2026-06-19-007).
 *
 * Mirrors the protocol-loader machinery (protocol-loader.ts): one file per
 * syllabus, an auto-generated index.yaml with a health rollup, a validate pass
 * that recomputes status, and an index rebuild hooked into paradigm_reindex.
 *
 * Storage layout:
 *   .paradigm/curriculum/
 *     index.yaml                # Auto-generated by reindex (summary + health)
 *     <agent-id>.syllabus       # One file per agent (YAML)
 *
 * A syllabus is the gated-class sign-off artifact: it pins the sources a learner
 * was certified against, the scope, the success criteria (breaking probes), and a
 * term TTL. validateSyllabus is the gate-zero instrument: a `stale`/`broken`/
 * `expired` syllabus refuses to run the autonomous study-hall unattended.
 *
 * Status semantics (recomputed at reindex):
 *   broken  — a sources[].ref no longer resolves (notebook entry / scenario gone).
 *   stale   — a referenced notebook entry was updated AFTER last_ratified.
 *   expired — now > last_ratified + term_ttl_days days.
 *   current — none of the above.
 */

import * as fs from 'fs';
import * as path from 'path';
import * as yaml from 'js-yaml';
import { log } from './mcp-logger.js';
import { loadNotebookEntries } from './notebook-loader.js';
import type { NotebookScope } from '../types/notebooks.js';

const CURRICULUM_DIR = '.paradigm/curriculum';
const INDEX_FILE = 'index.yaml';

// ────────────────────────────────────────────────────────
// Types
// ────────────────────────────────────────────────────────

export type SyllabusSourceKind = 'notebook' | 'scenario' | 'external';
export type SyllabusSourceTrust = 'certified' | 'provisional' | 'external';

export interface SyllabusSource {
  kind: SyllabusSourceKind;
  /** Reference id: a notebook entry id, a scenario id, or an external url/handle. */
  ref: string;
  trust?: SyllabusSourceTrust;
}

export interface SyllabusSuccessCriterion {
  /** A scenario id or probe description the learner must clear. */
  probe: string;
  must: 'survive' | 'reject';
}

export type SyllabusStatus = 'current' | 'stale' | 'broken' | 'expired';

export interface Syllabus {
  id: string;
  agent: string;
  version: number;
  sources: SyllabusSource[];
  scope: NotebookScope;
  success_criteria: SyllabusSuccessCriterion[];
  notebook_target: 'global' | 'local';
  approved_by?: string;
  approved_at?: string;
  /** Days the certification is valid; expiry = last_ratified + term_ttl_days. */
  term_ttl_days: number;
  status: SyllabusStatus;
  /** ISO timestamp of the most recent gated ratification (the term anchor). */
  last_ratified: string;
  /** Lore entry id this syllabus was ratified from. */
  recorded_from?: string;
}

export interface SyllabusIndexEntry {
  id: string;
  agent: string;
  version: number;
  status: SyllabusStatus;
  last_ratified: string;
  scope: NotebookScope;
}

export interface SyllabusIndex {
  version: string;
  generated: string;
  syllabi: SyllabusIndexEntry[];
  health: {
    total: number;
    current: number;
    stale: number;
    broken: number;
    expired: number;
  };
}

// ────────────────────────────────────────────────────────
// Read operations
// ────────────────────────────────────────────────────────

/** Load every syllabus from .paradigm/curriculum/. */
export async function loadSyllabi(rootDir: string): Promise<Syllabus[]> {
  const dir = path.join(rootDir, CURRICULUM_DIR);
  if (!fs.existsSync(dir)) return [];

  const files = fs.readdirSync(dir)
    .filter(f => f.endsWith('.syllabus'))
    .sort();

  const syllabi: Syllabus[] = [];
  for (const file of files) {
    try {
      const content = fs.readFileSync(path.join(dir, file), 'utf8');
      const syllabus = yaml.load(content) as Syllabus;
      if (syllabus?.id && syllabus?.agent) {
        syllabi.push(syllabus);
      }
    } catch {
      // Skip malformed files
    }
  }

  return syllabi;
}

/** Load the latest (highest-version) syllabus for an agent, or null. */
export async function loadLatestSyllabus(
  rootDir: string,
  agentId: string,
): Promise<Syllabus | null> {
  const filePath = path.join(rootDir, CURRICULUM_DIR, `${agentId}.syllabus`);
  if (fs.existsSync(filePath)) {
    try {
      const content = fs.readFileSync(filePath, 'utf8');
      const syllabus = yaml.load(content) as Syllabus;
      if (syllabus?.id) return syllabus;
    } catch {
      // fall through to scan
    }
  }

  // Fallback: scan all and pick the highest version for the agent.
  const all = await loadSyllabi(rootDir);
  const forAgent = all.filter(s => s.agent === agentId);
  if (forAgent.length === 0) return null;
  return forAgent.reduce((a, b) => (b.version > a.version ? b : a));
}

/** Load the syllabus index (auto-generated by reindex). */
export async function loadSyllabusIndex(rootDir: string): Promise<SyllabusIndex | null> {
  const indexPath = path.join(rootDir, CURRICULUM_DIR, INDEX_FILE);
  if (!fs.existsSync(indexPath)) return null;
  try {
    const content = fs.readFileSync(indexPath, 'utf8');
    return yaml.load(content) as SyllabusIndex;
  } catch {
    return null;
  }
}

// ────────────────────────────────────────────────────────
// Write operations
// ────────────────────────────────────────────────────────

/**
 * Record (or re-ratify) a syllabus. One file per agent: `<agent>.syllabus`.
 * If a syllabus already exists for the agent, the version is bumped (mirrors the
 * latest-wins single-file shape; the term anchor `last_ratified` is refreshed).
 */
export async function recordSyllabus(
  rootDir: string,
  syllabus: Omit<Syllabus, 'id' | 'version' | 'status' | 'last_ratified'> & {
    last_ratified?: string;
  },
): Promise<string> {
  const dir = path.join(rootDir, CURRICULUM_DIR);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  const now = new Date().toISOString();
  const filePath = path.join(dir, `${syllabus.agent}.syllabus`);

  // Bump version off any existing syllabus for this agent.
  let version = 1;
  if (fs.existsSync(filePath)) {
    try {
      const existing = yaml.load(fs.readFileSync(filePath, 'utf8')) as Syllabus;
      if (existing?.version) version = existing.version + 1;
    } catch {
      // treat unparseable as fresh
    }
  }

  const id = `SY-${syllabus.agent}`;

  const full: Syllabus = {
    id,
    agent: syllabus.agent,
    version,
    sources: syllabus.sources || [],
    scope: syllabus.scope,
    success_criteria: syllabus.success_criteria || [],
    notebook_target: syllabus.notebook_target,
    approved_by: syllabus.approved_by,
    approved_at: syllabus.approved_at || now,
    term_ttl_days: syllabus.term_ttl_days,
    status: 'current',
    last_ratified: syllabus.last_ratified || now,
    recorded_from: syllabus.recorded_from,
  };

  fs.writeFileSync(filePath, yaml.dump(full, { lineWidth: -1, noRefs: true }), 'utf8');
  return id;
}

// ────────────────────────────────────────────────────────
// Validation & Index Rebuild
// ────────────────────────────────────────────────────────

/**
 * Validate a syllabus: resolve every source ref, check staleness against the
 * referenced notebook's `updated`, and check TTL expiry. Returns the recomputed
 * status + the issues that produced it. Does NOT write — rebuildSyllabusIndex
 * persists the status.
 */
export function validateSyllabus(
  rootDir: string,
  syllabus: Syllabus,
): { status: SyllabusStatus; issues: string[] } {
  const issues: string[] = [];
  let status: SyllabusStatus = 'current';

  const ratifiedAt = Date.parse(syllabus.last_ratified);
  const ratifiedValid = !Number.isNaN(ratifiedAt);

  // Resolve referenced notebook entries + scenarios once.
  const notebookEntries = loadNotebookEntries(syllabus.agent, rootDir);
  const notebookById = new Map(notebookEntries.map(e => [e.id, e]));

  for (const src of syllabus.sources) {
    if (src.kind === 'notebook') {
      const entry = notebookById.get(src.ref);
      if (!entry) {
        issues.push(`Notebook source missing: ${src.ref}`);
        status = 'broken';
        continue;
      }
      // stale: a referenced notebook entry was updated after last_ratified.
      if (ratifiedValid && entry.updated) {
        const updatedAt = Date.parse(entry.updated);
        if (!Number.isNaN(updatedAt) && updatedAt > ratifiedAt) {
          issues.push(`Notebook source updated since ratification: ${src.ref}`);
          if (status !== 'broken') status = 'stale';
        }
      }
    } else if (src.kind === 'scenario') {
      // Scenario refs validated against the bank (cheap full load; banks are small).
      const scenarios = loadScenariosSync(rootDir);
      if (!scenarios.has(src.ref)) {
        issues.push(`Scenario source missing: ${src.ref}`);
        status = 'broken';
      }
    }
    // 'external' sources are not resolvable locally — trusted as-is.
  }

  // expired: now > last_ratified + term_ttl_days. Checked last so a `broken`
  // syllabus stays `broken` (the more actionable signal), but expiry still
  // overrides a `current`/`stale` reading.
  if (ratifiedValid && typeof syllabus.term_ttl_days === 'number') {
    const expiryAt = ratifiedAt + syllabus.term_ttl_days * 24 * 60 * 60 * 1000;
    if (Date.now() > expiryAt && status === 'current') {
      issues.push(`Term expired: ratified ${syllabus.last_ratified}, ttl ${syllabus.term_ttl_days}d`);
      status = 'expired';
    } else if (Date.now() > expiryAt && status === 'stale') {
      // An expired-AND-stale syllabus is still actionable as expired (kicks to gated).
      issues.push(`Term expired: ratified ${syllabus.last_ratified}, ttl ${syllabus.term_ttl_days}d`);
      status = 'expired';
    }
  }

  return { status, issues };
}

/** Lazily build a set of scenario ids (sync wrapper for validate). */
function loadScenariosSync(rootDir: string): Set<string> {
  try {
    // loadScenarios is async-shaped but reads sync fs underneath; we mirror its
    // file walk here to avoid awaiting inside the sync validate pass.
    const dir = path.join(rootDir, '.paradigm/curriculum/scenarios');
    if (!fs.existsSync(dir)) return new Set();
    const ids = new Set<string>();
    for (const file of fs.readdirSync(dir)) {
      if (!file.endsWith('.scenario')) continue;
      try {
        const s = yaml.load(fs.readFileSync(path.join(dir, file), 'utf8')) as { id?: string };
        if (s?.id) ids.add(s.id);
      } catch {
        // skip
      }
    }
    return ids;
  } catch {
    return new Set();
  }
}

/**
 * Validate all syllabi and rebuild index.yaml. Called during paradigm_reindex.
 * Persists each recomputed status back into its file (gate-zero must read it
 * from disk on the next study-hall run).
 */
export async function rebuildSyllabusIndex(rootDir: string): Promise<SyllabusIndex> {
  const syllabi = await loadSyllabi(rootDir);
  const entries: SyllabusIndexEntry[] = [];
  let current = 0;
  let stale = 0;
  let broken = 0;
  let expired = 0;

  for (const syllabus of syllabi) {
    const validation = validateSyllabus(rootDir, syllabus);

    if (syllabus.status !== validation.status) {
      syllabus.status = validation.status;
      const filePath = path.join(rootDir, CURRICULUM_DIR, `${syllabus.agent}.syllabus`);
      if (fs.existsSync(filePath)) {
        fs.writeFileSync(filePath, yaml.dump(syllabus, { lineWidth: -1, noRefs: true }), 'utf8');
      }
    }

    switch (validation.status) {
      case 'current': current++; break;
      case 'stale': stale++; break;
      case 'broken': broken++; break;
      case 'expired': expired++; break;
    }

    entries.push({
      id: syllabus.id,
      agent: syllabus.agent,
      version: syllabus.version,
      status: validation.status,
      last_ratified: syllabus.last_ratified,
      scope: syllabus.scope,
    });
  }

  const index: SyllabusIndex = {
    version: '1.0',
    generated: new Date().toISOString(),
    syllabi: entries,
    health: { total: syllabi.length, current, stale, broken, expired },
  };

  const dir = path.join(rootDir, CURRICULUM_DIR);
  if (syllabi.length > 0) {
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(
      path.join(dir, INDEX_FILE),
      yaml.dump(index, { lineWidth: -1, noRefs: true }),
      'utf8',
    );
  }

  if (broken > 0 || expired > 0) {
    log.component('#syllabus-loader').warn('syllabi require re-ratification', {
      broken,
      expired,
      stale,
    });
  }

  return index;
}
